### ISSUE TITLE
SQLite demo fails to build on Linux

### ISSUE THREAD

**Issue by Pharmhaus-2** [blitz-foundation/monkey2#130]
Original Author: jondecker76

`Mx2cc version 1.1.15

***** Making app '/home/viavacavi/Dropbox/monkey2/bananas/sqlitetest/sqlitetest.monkey2' (linux release x64 gcc) *****

Parsing...
Semanting...
Translating...
Compiling...
Linking /home/viavacavi/Dropbox/monkey2/bananas/sqlitetest/sqlitetest.products/Linux/Sqlitetest...
Build error: System command failed:

g++  -s -O3 -o "/home/viavacavi/Dropbox/monkey2/bananas/sqlitetest/sqlitetest.products/Linux/Sqlitetest" "/home/viavacavi/Dropbox/monkey2/bananas/sqlitetest/sqlitetest.buildv1.1.15/linux_release/build/r5b58089e.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/bananas/sqlitetest/sqlitetest.buildv1.1.15/linux_release/build/r73a64ed5.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/bananas/sqlitetest/sqlitetest.buildv1.1.15/linux_release/build/r4d8c9f55.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/bananas/sqlitetest/sqlitetest.buildv1.1.15/linux_release/build/r897528f5.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/bananas/sqlitetest/sqlitetest.buildv1.1.15/linux_release/build/sqlitetestb4f98a14.cpp.o" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a" "/home/viavacavi/Dropbox/monkey2/modules/libc/libc.buildv1.1.15/linux_release/libc.a" "/home/viavacavi/Dropbox/monkey2/modules/monkey/monkey.buildv1.1.15/linux_release/monkey.a" 

/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `pthreadMutexTry':
sqlite3.c:(.text+0x44c5): undefined reference to `pthread_mutex_trylock'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `vdbeIncrFree':
sqlite3.c:(.text+0xb908): undefined reference to `pthread_join'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `vdbePmaReaderNext':
sqlite3.c:(.text+0xecca): undefined reference to `pthread_join'
/usr/bin/ld: sqlite3.c:(.text+0xece8): undefined reference to `pthread_create'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `pthreadMutexAlloc':
sqlite3.c:(.text+0x120b7): undefined reference to `pthread_mutexattr_init'
/usr/bin/ld: sqlite3.c:(.text+0x120c4): undefined reference to `pthread_mutexattr_settype'
/usr/bin/ld: sqlite3.c:(.text+0x120d7): undefined reference to `pthread_mutexattr_destroy'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `vdbeSorterFlushPMA':
sqlite3.c:(.text+0x13be4): undefined reference to `pthread_join'
/usr/bin/ld: sqlite3.c:(.text+0x13d18): undefined reference to `pthread_create'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `sqlite3VdbeSorterReset':
sqlite3.c:(.text+0x164ea): undefined reference to `pthread_join'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `vdbeMergeEngineInit':
sqlite3.c:(.text+0x1d3a8): undefined reference to `pthread_create'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `unixDlError':
sqlite3.c:(.text+0x29d8f): undefined reference to `dlerror'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `sqlite3VdbeExec':
sqlite3.c:(.text+0x84e97): undefined reference to `pthread_join'
/usr/bin/ld: sqlite3.c:(.text+0x89da2): undefined reference to `pthread_create'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `unixDlClose':
sqlite3.c:(.text+0x4a24): undefined reference to `dlclose'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `unixDlSym':
sqlite3.c:(.text+0x4a37): undefined reference to `dlsym'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `unixDlOpen':
sqlite3.c:(.text+0x4a49): undefined reference to `dlopen'
collect2: error: ld returned 1 exit status

***** Fatal mx2cc error *****

Internal mx2cc build error
`

**Comment by Pharmhaus-2** [comment]
@jondecker76 which distro are you using?
Any custom env_linux.txt configuration?

**Comment by jondecker76** [comment]
This has been fixed in a recent update!
